#pragma once

#include <LittleFS.h>
#include "menu_page.hpp"
#include "menu.hpp"
#include "debug_logger.hpp"

// Forward Declaration
class FileMenuPage;

/**
 * @brief A special menu page for displaying options for a specific file
 * @details An automatically generated page which gives the options avaialble for manipulatiing a
 * selected file. The user should never need to manually create a page of this type as it will be
 * automatically generated by the FileMenuPage class.
 * @ingroup Menu
 */
class FileOptMenuPg : public MenuPage {
public:
    ~FileOptMenuPg() = default;

private:
    /**
     * @brief Construct a new FileOptMenuPg object
     * @details The constructor is made private so it is only constructable by the FileMenuPage friend class
     * 
     * @param lbl - The label to refer to this page by
     * @param parentLbl - The page label to return to upon selecting the "back" option
     * @param file - The file being manipulated
     */
    FileOptMenuPg(const std::string& lbl, const std::string& parentLbl, const std::string& file);
    
    /**
     * @brief Called upon requesting the deletion of the selected file. Deletes the file.
     * 
     */
    void onFileDelete();

    /**
     * @brief Called upon requesting a file be printed. Prints the contents of the file onto the serial connection.
     * 
     */
    void onFilePrint();

    std::string selectedFile;
    std::string parentMenuLbl;

    friend class FileMenuPage;
};