/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.contacteditor;
import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.*;
import javax.imageio.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JToggleButton;
/**
 *
 * @author tojo9
 */
    
public class NewJFrame extends javax.swing.JFrame {
    //this variable saves which button is currently selected 
    private int saveButton;
    // Declare and initialize an ArrayList to hold JToggleButtons
    private ArrayList<JToggleButton> toggleButtonList = new ArrayList<>(); 
    private int colSize = 3;
    private int rowSize = 3;
    private int initialSize = 100;
    private int scaleBy = 10;
    
    
    //initializes the rotation for each road square
        //each rotation is 90 degrees apart
    private int rotate[] = new int[25]; 
    
    //initializes the road type for each road square
        //type -1 = blank
        //type 0 = straight road
        //type 1 = curved road
        //type 2 = 3-way-intersection
        //type 3 = 4-way-intersection
        //type 4 = 3-way-intersection-mirrored 
    private int road[] = new int[25];
    JPanel panel = new JPanel();
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        jScrollPane1.setViewportView(panel);

        
    }
    
     private void JB4Action() {
        panel.setLayout(new GridLayout(rowSize, colSize)); // Set layout to vertical
        for(int i = 0; i < rowSize*colSize; i++){
            createButtons();
        }
        
        setIcon();  
        
    }
     private void createButtons(){
        // Add the panel to the JScrollPane      
        JToggleButton button = new JToggleButton();
        button.setBorder(null);
        
        final int buttonIndex = toggleButtonList.size();
        
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                saveButton = buttonIndex;
                if (button.isSelected()) {
                    
                    // The button was toggled on
                    System.out.println("Button " + buttonIndex + " was toggled ON.");
                } else {
                    // The button was toggled off
                    System.out.println("Button " + buttonIndex + " was toggled OFF.");
                }
        }});
        panel.add(button); // Add the button to jPanel1
        toggleButtonList.add(button); // Add the button to the ArrayList
     }
     private void setIcon(){
                   
            updateIconSize();

            // Force layout update to reflect changes
            panel.revalidate();
            panel.repaint();
        
     }
     private void scaleUp(){
         scaleBy = scaleBy + 10;
     }
    
     private void scaleDown(){
         scaleBy = scaleBy - 10;
     
     }
     private void updateIconSize(){
        try {   
            // Load image from file
            Image img = ImageIO.read(NewJFrame.class.getResource(IconSelect(road[saveButton], rotate[saveButton])));

            // Create ImageIcon from loaded image
            ImageIcon icon = new ImageIcon(img);
            Image scaledImage = img.getScaledInstance(initialSize + scaleBy, initialSize + scaleBy, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);
                        // Update icons for components
            toggleButtonList.get(0).setIcon(scaledIcon);
            toggleButtonList.get(1).setIcon(scaledIcon);
            toggleButtonList.get(2).setIcon(scaledIcon);
            toggleButtonList.get(3).setIcon(scaledIcon);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading image: " + e.getMessage(), "Image Loading Error", JOptionPane.ERROR_MESSAGE);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleRoad4 = new javax.swing.JToggleButton();
        jToggleRoad5 = new javax.swing.JToggleButton();
        jToggleRoad6 = new javax.swing.JToggleButton();
        jToggleRoad7 = new javax.swing.JToggleButton();
        jToggleRoad8 = new javax.swing.JToggleButton();
        jToggleRoad9 = new javax.swing.JToggleButton();
        jToggleRoad10 = new javax.swing.JToggleButton();
        jToggleRoad11 = new javax.swing.JToggleButton();
        jToggleRoad12 = new javax.swing.JToggleButton();
        jToggleRoad13 = new javax.swing.JToggleButton();
        jToggleRoad14 = new javax.swing.JToggleButton();
        jToggleRoad15 = new javax.swing.JToggleButton();
        jToggleRoad16 = new javax.swing.JToggleButton();
        jToggleRoad17 = new javax.swing.JToggleButton();
        jToggleRoad18 = new javax.swing.JToggleButton();
        jToggleRoad19 = new javax.swing.JToggleButton();
        jToggleRoad20 = new javax.swing.JToggleButton();
        jToggleRoad21 = new javax.swing.JToggleButton();
        jToggleRoad22 = new javax.swing.JToggleButton();
        jToggleRoad23 = new javax.swing.JToggleButton();
        jToggleRoad24 = new javax.swing.JToggleButton();
        jToggleRoad25 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelStraightRoad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jToggleRoad2 = new javax.swing.JToggleButton();
        jToggleRoad1 = new javax.swing.JToggleButton();
        jToggleRoad3 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jToggleRoad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad4ActionPerformed(evt);
            }
        });

        jToggleRoad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad5ActionPerformed(evt);
            }
        });

        jToggleRoad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad6ActionPerformed(evt);
            }
        });

        jToggleRoad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad7ActionPerformed(evt);
            }
        });

        jToggleRoad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad8ActionPerformed(evt);
            }
        });

        jToggleRoad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad9ActionPerformed(evt);
            }
        });

        jToggleRoad10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad10ActionPerformed(evt);
            }
        });

        jToggleRoad11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad11ActionPerformed(evt);
            }
        });

        jToggleRoad12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad12ActionPerformed(evt);
            }
        });

        jToggleRoad13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad13ActionPerformed(evt);
            }
        });

        jToggleRoad14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad14ActionPerformed(evt);
            }
        });

        jToggleRoad15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad15ActionPerformed(evt);
            }
        });

        jToggleRoad16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad16ActionPerformed(evt);
            }
        });

        jToggleRoad17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad17ActionPerformed(evt);
            }
        });

        jToggleRoad18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad18ActionPerformed(evt);
            }
        });

        jToggleRoad19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad19ActionPerformed(evt);
            }
        });

        jToggleRoad20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad20ActionPerformed(evt);
            }
        });

        jToggleRoad21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad21ActionPerformed(evt);
            }
        });

        jToggleRoad22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad22ActionPerformed(evt);
            }
        });

        jToggleRoad23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad23ActionPerformed(evt);
            }
        });

        jToggleRoad24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad24ActionPerformed(evt);
            }
        });

        jToggleRoad25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad0ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Size");
        jLabel1.setAutoscrolls(true);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("colomn");

        jLabel3.setText("row");

        jLabelStraightRoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png"))); // NOI18N
        jLabelStraightRoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelStraightRoadMouseReleased(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3WayIntersectionMouseReleased(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCurveRoadMouseReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4WayIntersectionMouseReleased(evt);
            }
        });

        jButton1.setText("rotate road");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRotate(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton1KeyReleased(evt);
            }
        });

        jButton2.setText("mirror 3-way");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMirror(evt);
            }
        });

        jButton3.setText("delete road");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelete(evt);
            }
        });

        jButton4.setText("add buttons");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("scale up");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleUp(evt);
            }
        });

        jButton6.setText("scale down");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleDown(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel3))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelStraightRoad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton6)
                                    .addComponent(jButton5))))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStraightRoad)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleRoad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad2ActionPerformed(evt);
            }
        });

        jToggleRoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad1ActionPerformed(evt);
            }
        });

        jToggleRoad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleRoad21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleRoad11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jToggleRoad12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jToggleRoad13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jToggleRoad14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jToggleRoad15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jToggleRoad1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleRoad4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jToggleRoad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jToggleRoad7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleRoad16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /*jToggleRoad1ActionPerformed - jToggleRoad25AcionPerformed 
        the botton selected by the user is saved and calls ButtonToggle which  
        actives the button and any other button that was selected is deselected  
        so only one button is currently selected 
    */
    private void jToggleRoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad1ActionPerformed
            saveButton = 1;
            ButtonToggle(saveButton);     
    }//GEN-LAST:event_jToggleRoad1ActionPerformed
    private void jToggleRoad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad2ActionPerformed
            saveButton = 2;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad2ActionPerformed
    private void jToggleRoad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad3ActionPerformed
            saveButton = 3;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad3ActionPerformed
    private void jToggleRoad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad4ActionPerformed
            saveButton = 4;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad4ActionPerformed
    private void jToggleRoad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad5ActionPerformed
            saveButton = 5;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad5ActionPerformed
    private void jToggleRoad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad6ActionPerformed
            saveButton = 6;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad6ActionPerformed
    private void jToggleRoad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad7ActionPerformed
            saveButton = 7;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad7ActionPerformed
    private void jToggleRoad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad8ActionPerformed
            saveButton = 8;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad8ActionPerformed
    private void jToggleRoad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad9ActionPerformed
            saveButton = 9;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad9ActionPerformed
    private void jToggleRoad10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad10ActionPerformed
            saveButton = 10;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad10ActionPerformed
    private void jToggleRoad11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad11ActionPerformed
            saveButton = 11;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad11ActionPerformed
    private void jToggleRoad12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad12ActionPerformed
            saveButton = 12;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad12ActionPerformed
    private void jToggleRoad13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad13ActionPerformed
            saveButton = 13;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad13ActionPerformed
    private void jToggleRoad14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad14ActionPerformed
            saveButton = 14;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad14ActionPerformed
    private void jToggleRoad15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad15ActionPerformed
            saveButton = 15;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad15ActionPerformed
    private void jToggleRoad16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad16ActionPerformed
            saveButton = 16;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad16ActionPerformed
    private void jToggleRoad17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad17ActionPerformed
            saveButton = 17;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad17ActionPerformed
    private void jToggleRoad18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad18ActionPerformed
            saveButton = 18;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad18ActionPerformed
    private void jToggleRoad19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad19ActionPerformed
            saveButton = 19;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad19ActionPerformed
    private void jToggleRoad20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad20ActionPerformed
            saveButton = 20;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad20ActionPerformed
    private void jToggleRoad21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad21ActionPerformed
            saveButton = 21;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad21ActionPerformed
    private void jToggleRoad22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad22ActionPerformed
            saveButton = 22;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad22ActionPerformed
    private void jToggleRoad23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad23ActionPerformed
            saveButton = 23;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad23ActionPerformed
    private void jToggleRoad24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad24ActionPerformed
            saveButton = 24;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad24ActionPerformed
    private void jToggleRoad0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad0ActionPerformed
            saveButton = 0;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad0ActionPerformed

    //sets the currently selected tile to a curved road
    private void jLabelCurveRoadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCurveRoadMouseReleased
        //sets road type to curved road
        road[saveButton] = 1;                                       
        rotate[saveButton] = 0;
        
        //calls the function that inserts the needed icon
        IconInsert(); 
    }//GEN-LAST:event_jLabelCurveRoadMouseReleased
    
   
    //sets the currently selected tile to a 4-way-intersection
    private void jLabel4WayIntersectionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4WayIntersectionMouseReleased
        //sets road type to 4-way
        road[saveButton] = 3;                                       
        rotate[saveButton] = 0;
        
        //calls the function that inserts the needed icon
        IconInsert(); 
    }//GEN-LAST:event_jLabel4WayIntersectionMouseReleased

    //sets the currently selected tile to a straight road
    private void jLabelStraightRoadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStraightRoadMouseReleased
        //sets road type to straight road
        road[saveButton] = 0;                    
        rotate[saveButton] = 0;
        
        //calls the function that inserts the needed icon
        IconInsert(); 
    }//GEN-LAST:event_jLabelStraightRoadMouseReleased

    private void jButtonRotate(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRotate
        if(rotate[saveButton] < 3){
                rotate[saveButton] = rotate[saveButton] + 1;                                                    
            }
            else{
                rotate[saveButton] = 0;
            }
        IconInsert();
    }//GEN-LAST:event_jButtonRotate
    
    //sets the currently selected tile to a 3-way-intersection-mirrored 
    private void jButtonMirror(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMirror
        //toggles between a mirrored 3-way and the original 3-way
        if (road[saveButton] == 4){
            //sets to normal 3-way
            road[saveButton] = 2;  
            
            //mirrors along the axis from mirrored to normal
            if (rotate[saveButton] < 1){
            rotate[saveButton] = rotate[saveButton] + 3;
            }
            else{
                rotate[saveButton] = rotate[saveButton] - 1;
            }
        }
        else{
            //sets to mirrored 3-way
            road[saveButton] = 4;
            
            //mirrors along the axis from normal to mirrored 
            if (rotate[saveButton] < 3){
                rotate[saveButton] = rotate[saveButton] + 1;
            }
            else{
                rotate[saveButton] = rotate[saveButton] - 3;
            }
        }
        
        //calls the function that inserts the needed icon
        IconInsert();
    }//GEN-LAST:event_jButtonMirror
 
    //deletes icon and sets to blank
    private void jButtonDelete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelete
        //sets road type to Blank
        road[saveButton] = -1;
        
        //sets blank icon
        IconInsert();
    }//GEN-LAST:event_jButtonDelete

    private void jButton1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JB4Action();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void scaleUp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleUp
        scaleUp();
        setIcon();
    }//GEN-LAST:event_scaleUp

    private void scaleDown(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleDown
        scaleDown();
        setIcon();
    }//GEN-LAST:event_scaleDown

//GEN-FIRST:event_jLabel3WayIntersectionMouseReleased
 
//GEN-LAST:event_jLabel3WayIntersectionMouseReleased

    //toggles road tiles so only one tile can be pressed at once
    private void ButtonToggle(int BNum){
        //sets all tiles selected to false
        jToggleRoad1.setSelected(false);
        jToggleRoad2.setSelected(false);
        jToggleRoad3.setSelected(false);
        jToggleRoad4.setSelected(false);
        jToggleRoad5.setSelected(false);
        jToggleRoad6.setSelected(false);
        jToggleRoad7.setSelected(false);
        jToggleRoad8.setSelected(false);
        jToggleRoad9.setSelected(false);
        jToggleRoad10.setSelected(false);
        jToggleRoad11.setSelected(false);
        jToggleRoad12.setSelected(false);
        jToggleRoad13.setSelected(false);
        jToggleRoad14.setSelected(false);
        jToggleRoad15.setSelected(false);
        jToggleRoad16.setSelected(false);
        jToggleRoad17.setSelected(false);
        jToggleRoad18.setSelected(false);
        jToggleRoad19.setSelected(false);
        jToggleRoad20.setSelected(false);
        jToggleRoad21.setSelected(false);
        jToggleRoad22.setSelected(false);
        jToggleRoad23.setSelected(false);
        jToggleRoad24.setSelected(false);
        jToggleRoad25.setSelected(false);

        //finds the tile currently selected and turns the selection on
        switch (BNum){
                case 0:
                    jToggleRoad25.setSelected(true);
                    break;
                case 1:
                    jToggleRoad1.setSelected(true);
                    break;
                case 2:
                    jToggleRoad2.setSelected(true);
                    break; 
                case 3:
                    jToggleRoad3.setSelected(true);
                    break;
                case 4:
                    jToggleRoad4.setSelected(true);
                    break;
                case 5:
                    jToggleRoad5.setSelected(true);
                    break;
                case 6:
                    jToggleRoad6.setSelected(true);
                    break;
                case 7:
                    jToggleRoad7.setSelected(true);
                    break;
                case 8:
                    jToggleRoad8.setSelected(true);
                    break;
                case 9:
                    jToggleRoad9.setSelected(true);
                    break;
                case 10:
                    jToggleRoad10.setSelected(true);
                    break;
                case 11:
                    jToggleRoad11.setSelected(true);
                    break;
                case 12:
                    jToggleRoad12.setSelected(true);
                    break;
                case 13:
                    jToggleRoad13.setSelected(true);
                    break;
                case 14:
                    jToggleRoad14.setSelected(true);
                    break;
                case 15:
                    jToggleRoad15.setSelected(true);
                    break;
                case 16:
                    jToggleRoad16.setSelected(true);
                    break;
                case 17:
                    jToggleRoad17.setSelected(true);
                    break;
                case 18:
                    jToggleRoad18.setSelected(true);
                    break;
                case 19:
                    jToggleRoad19.setSelected(true);
                    break;
                case 20:
                    jToggleRoad20.setSelected(true);
                    break;
                case 21:    
                    jToggleRoad21.setSelected(true);
                    break;
                case 22:
                    jToggleRoad22.setSelected(true);
                    break;
                case 23:
                    jToggleRoad23.setSelected(true);
                    break;
                case 24:
                    jToggleRoad24.setSelected(true);
                    break;
                       
                    
    }
}
    
    //sets the selected road tile to a specific icon
    private void IconInsert(){
            //selects the tile that will have it's icon changed
            switch (saveButton){  
                
                //uses the road type and rotation to call the IconSelect function which selects the icon
                //once the icon is selected the icon is set to the road tile selected
                case 1:                  
                    jToggleRoad1.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));    
                    break;
                case 2:
                    jToggleRoad2.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break; 
                case 3:
                    jToggleRoad3.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 4:
                    jToggleRoad4.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 5:
                    jToggleRoad5.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 6:
                    jToggleRoad6.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 7:
                    jToggleRoad7.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 8:
                    jToggleRoad8.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 9:
                    jToggleRoad9.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 10:
                    jToggleRoad10.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 11:
                    jToggleRoad11.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 12:
                    jToggleRoad12.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 13:
                    jToggleRoad13.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 14:
                    jToggleRoad14.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 15:
                    jToggleRoad15.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 16:
                    jToggleRoad16.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 17:
                    jToggleRoad17.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 18:
                    jToggleRoad18.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 19:
                    jToggleRoad19.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 20:
                    jToggleRoad20.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 21:    
                    jToggleRoad21.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 22:
                    jToggleRoad22.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 23:
                    jToggleRoad23.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 24:
                    jToggleRoad24.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
                case 0:         
                    jToggleRoad25.setIcon(new javax.swing.ImageIcon(getClass().getResource(IconSelect(road[saveButton], rotate[saveButton]))));
                    break;
        }
    }
    
    //finds the icon for each specific case
    private String IconSelect(int RoadType, int RotateNum){
        //sets icon to blank
        String icon = "";
        
        //finds which road type is being used
            //sets the varible icon to the image file path
        switch (RoadType){
            case 0:
                switch (RotateNum){
                    case 0:
                        icon = "/images/straight-road.png";
                        break;
                    case 1:
                        icon = "/images/straight-road-R1.png";
                        break;
                    case 2:
                        icon = "/images/straight-road-R2.png";
                        break;
                    case 3:
                        icon = "/images/straight-road-R3.png";
                        break;
                }
                break;
            case 1:
                switch (RotateNum){
                    case 0:
                        icon = "/images/curve-road.png";
                        break;
                    case 1:
                        icon = "/images/curve-road-R1.png";
                        break;
                    case 2:
                        icon = "/images/curve-road-R2.png";
                        break;
                    case 3:
                        icon = "/images/curve-road-R3.png";
                        break;
                }
                break;
            case 2:
                switch (RotateNum){
                    case 0:
                        icon = "/images/3-way-intersection.png";
                        break;
                    case 1:
                        icon = "/images/3-way-intersection-R1.png";
                        break;
                    case 2:
                        icon = "/images/3-way-intersection-R2.png";
                        break;
                    case 3:
                        icon = "/images/3-way-intersection-R3.png";
                        break;
                }
                break;
            case 3:
                switch (RotateNum){
                    case 0:
                        icon = "/images/4-way-intersection.png";
                        break;
                    case 1:
                        icon = "/images/4-way-intersection-R1.png";
                        break;
                    case 2:
                        icon = "/images/4-way-intersection-R2.png";
                        break;
                    case 3:
                        icon = "/images/4-way-intersection-R3.png";
                        break;
                }
                break; 
            case 4:
                switch (RotateNum){
                    case 0:
                        icon = "/images/3-way-intersection.mirror.png";
                        break;
                    case 1:
                        icon = "/images/3-way-intersection.mirror-R1.png";
                        break;
                    case 2:
                        icon = "/images/3-way-intersection.mirror-R2.png";
                        break;
                    case 3:
                        icon = "/images/3-way-intersection.mirror-R3.png";
                        break;
                }
                break;
        }
        
        //returns the file path to the image
        return(icon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelStraightRoad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleRoad1;
    private javax.swing.JToggleButton jToggleRoad10;
    private javax.swing.JToggleButton jToggleRoad11;
    private javax.swing.JToggleButton jToggleRoad12;
    private javax.swing.JToggleButton jToggleRoad13;
    private javax.swing.JToggleButton jToggleRoad14;
    private javax.swing.JToggleButton jToggleRoad15;
    private javax.swing.JToggleButton jToggleRoad16;
    private javax.swing.JToggleButton jToggleRoad17;
    private javax.swing.JToggleButton jToggleRoad18;
    private javax.swing.JToggleButton jToggleRoad19;
    private javax.swing.JToggleButton jToggleRoad2;
    private javax.swing.JToggleButton jToggleRoad20;
    private javax.swing.JToggleButton jToggleRoad21;
    private javax.swing.JToggleButton jToggleRoad22;
    private javax.swing.JToggleButton jToggleRoad23;
    private javax.swing.JToggleButton jToggleRoad24;
    private javax.swing.JToggleButton jToggleRoad25;
    private javax.swing.JToggleButton jToggleRoad3;
    private javax.swing.JToggleButton jToggleRoad4;
    private javax.swing.JToggleButton jToggleRoad5;
    private javax.swing.JToggleButton jToggleRoad6;
    private javax.swing.JToggleButton jToggleRoad7;
    private javax.swing.JToggleButton jToggleRoad8;
    private javax.swing.JToggleButton jToggleRoad9;
    // End of variables declaration//GEN-END:variables
}
