/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.contacteditor;

/**
 *
 * @author tojo9
 */
public class NewJFrame extends javax.swing.JFrame {
     private int saveButton;
     private int rotate1;
     private int rotate2;
     private int rotate3;
     private int rotate4;
     private int rotate5;
     private int rotate6;
     private int rotate7;
     private int rotate8;
     private int rotate9;
     private int rotate10;
     private int rotate11;
     private int rotate12;
     private int rotate13;
     private int rotate14;
     private int rotate15;
     private int rotate16;
     private int rotate17;
     private int rotate18;
     private int rotate19;
     private int rotate20;
     private int rotate21;
     private int rotate22;
     private int rotate23;
     private int rotate24;
     private int rotate25;
     private int road1;
     private int road2;
     private int road3;
     private int road4;
     private int road5;
     private int road6;
     private int road7;
     private int road8;
     private int road9;
     private int road10;
     private int road11;
     private int road12;
     private int road13;
     private int road14;
     private int road15;
     private int road16;
     private int road17;
     private int road18;
     private int road19;
     private int road20;
     private int road21;
     private int road22;
     private int road23;
     private int road24;
     private int road25;
     
     
             
     
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleRoad4 = new javax.swing.JToggleButton();
        jToggleRoad5 = new javax.swing.JToggleButton();
        jToggleRoad6 = new javax.swing.JToggleButton();
        jToggleRoad7 = new javax.swing.JToggleButton();
        jToggleRoad8 = new javax.swing.JToggleButton();
        jToggleRoad9 = new javax.swing.JToggleButton();
        jToggleRoad10 = new javax.swing.JToggleButton();
        jToggleRoad11 = new javax.swing.JToggleButton();
        jToggleRoad12 = new javax.swing.JToggleButton();
        jToggleRoad13 = new javax.swing.JToggleButton();
        jToggleRoad14 = new javax.swing.JToggleButton();
        jToggleRoad15 = new javax.swing.JToggleButton();
        jToggleRoad16 = new javax.swing.JToggleButton();
        jToggleRoad17 = new javax.swing.JToggleButton();
        jToggleRoad18 = new javax.swing.JToggleButton();
        jToggleRoad19 = new javax.swing.JToggleButton();
        jToggleRoad20 = new javax.swing.JToggleButton();
        jToggleRoad21 = new javax.swing.JToggleButton();
        jToggleRoad22 = new javax.swing.JToggleButton();
        jToggleRoad23 = new javax.swing.JToggleButton();
        jToggleRoad24 = new javax.swing.JToggleButton();
        jToggleRoad25 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelStraightRoad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleRoad2 = new javax.swing.JToggleButton();
        jToggleRoad1 = new javax.swing.JToggleButton();
        jToggleRoad3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jToggleRoad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad4ActionPerformed(evt);
            }
        });

        jToggleRoad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad5ActionPerformed(evt);
            }
        });

        jToggleRoad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad6ActionPerformed(evt);
            }
        });

        jToggleRoad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad7ActionPerformed(evt);
            }
        });

        jToggleRoad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad8ActionPerformed(evt);
            }
        });

        jToggleRoad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad9ActionPerformed(evt);
            }
        });

        jToggleRoad10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad10ActionPerformed(evt);
            }
        });

        jToggleRoad11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad11ActionPerformed(evt);
            }
        });

        jToggleRoad12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad12ActionPerformed(evt);
            }
        });

        jToggleRoad13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad13ActionPerformed(evt);
            }
        });

        jToggleRoad14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad14ActionPerformed(evt);
            }
        });

        jToggleRoad15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad15ActionPerformed(evt);
            }
        });

        jToggleRoad16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad16ActionPerformed(evt);
            }
        });

        jToggleRoad17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad17ActionPerformed(evt);
            }
        });

        jToggleRoad18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad18ActionPerformed(evt);
            }
        });

        jToggleRoad19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad19ActionPerformed(evt);
            }
        });

        jToggleRoad20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad20ActionPerformed(evt);
            }
        });

        jToggleRoad21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad21ActionPerformed(evt);
            }
        });

        jToggleRoad22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad22ActionPerformed(evt);
            }
        });

        jToggleRoad23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad23ActionPerformed(evt);
            }
        });

        jToggleRoad24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad24ActionPerformed(evt);
            }
        });

        jToggleRoad25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad25ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Size");
        jLabel1.setAutoscrolls(true);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("colomn");

        jLabel3.setText("row");

        jLabelStraightRoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png"))); // NOI18N
        jLabelStraightRoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelStraightRoadMouseReleased(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel3WayIntersectionMouseReleased(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelCurveRoadMouseReleased(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4WayIntersectionMouseReleased(evt);
            }
        });

        jButton1.setText("rotate road");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel3))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelStraightRoad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStraightRoad)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleRoad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad2ActionPerformed(evt);
            }
        });

        jToggleRoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad1ActionPerformed(evt);
            }
        });

        jToggleRoad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleRoad3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleRoad21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jToggleRoad11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jToggleRoad12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jToggleRoad13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jToggleRoad14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jToggleRoad15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jToggleRoad1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jToggleRoad4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, 0)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jToggleRoad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jToggleRoad7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, 0)
                                    .addComponent(jToggleRoad10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToggleRoad16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jToggleRoad20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleRoad21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleRoad25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jToggleRoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad1ActionPerformed
            saveButton = 1;
            ButtonToggle(saveButton);     
    }//GEN-LAST:event_jToggleRoad1ActionPerformed

    private void jToggleRoad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad2ActionPerformed
            saveButton = 2;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad2ActionPerformed

    private void jLabelStraightRoadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelStraightRoadMouseReleased
        switch (saveButton){
                case 1:
                    jToggleRoad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 2:
                    jToggleRoad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break; 
                case 3:
                    jToggleRoad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 4:
                    jToggleRoad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 5:
                    jToggleRoad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 6:
                    jToggleRoad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 7:
                    jToggleRoad7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 8:
                    jToggleRoad8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 9:
                    jToggleRoad9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 10:
                    jToggleRoad10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 11:
                    jToggleRoad11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 12:
                    jToggleRoad12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 13:
                    jToggleRoad13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 14:
                    jToggleRoad14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 15:
                    jToggleRoad15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 16:
                    jToggleRoad16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 17:
                    jToggleRoad17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 18:
                    jToggleRoad18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 19:
                    jToggleRoad19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 20:
                    jToggleRoad20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 21:    
                    jToggleRoad21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 22:
                    jToggleRoad22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 23:
                    jToggleRoad23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 24:
                    jToggleRoad24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
                case 25:         
                    jToggleRoad25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/straight-road.png")));
                    RotateIcon(0, saveButton, 0);
                    break;
        }
        
    }//GEN-LAST:event_jLabelStraightRoadMouseReleased

    private void jToggleRoad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad3ActionPerformed
            saveButton = 3;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad3ActionPerformed

    private void jToggleRoad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad4ActionPerformed
            saveButton = 4;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad4ActionPerformed

    private void jToggleRoad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad5ActionPerformed
            saveButton = 5;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad5ActionPerformed

    private void jToggleRoad6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad6ActionPerformed
            saveButton = 6;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad6ActionPerformed

    private void jToggleRoad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad7ActionPerformed
            saveButton = 7;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad7ActionPerformed

    private void jToggleRoad8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad8ActionPerformed
            saveButton = 8;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad8ActionPerformed

    private void jToggleRoad9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad9ActionPerformed
            saveButton = 9;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad9ActionPerformed

    private void jToggleRoad10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad10ActionPerformed
            saveButton = 10;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad10ActionPerformed

    private void jToggleRoad11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad11ActionPerformed
            saveButton = 11;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad11ActionPerformed

    private void jToggleRoad12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad12ActionPerformed
            saveButton = 12;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad12ActionPerformed

    private void jToggleRoad13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad13ActionPerformed
            saveButton = 13;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad13ActionPerformed

    private void jToggleRoad14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad14ActionPerformed
            saveButton = 14;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad14ActionPerformed

    private void jToggleRoad15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad15ActionPerformed
            saveButton = 15;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad15ActionPerformed

    private void jToggleRoad16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad16ActionPerformed
            saveButton = 16;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad16ActionPerformed

    private void jToggleRoad17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad17ActionPerformed
            saveButton = 17;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad17ActionPerformed

    private void jToggleRoad18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad18ActionPerformed
            saveButton = 18;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad18ActionPerformed

    private void jToggleRoad19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad19ActionPerformed
            saveButton = 19;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad19ActionPerformed

    private void jToggleRoad20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad20ActionPerformed
            saveButton = 20;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad20ActionPerformed

    private void jToggleRoad21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad21ActionPerformed
            saveButton = 21;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad21ActionPerformed

    private void jToggleRoad22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad22ActionPerformed
            saveButton = 22;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad22ActionPerformed

    private void jToggleRoad23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad23ActionPerformed
            saveButton = 23;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad23ActionPerformed

    private void jToggleRoad24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad24ActionPerformed
            saveButton = 24;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad24ActionPerformed

    private void jToggleRoad25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleRoad25ActionPerformed
            saveButton = 25;
            ButtonToggle(saveButton);
    }//GEN-LAST:event_jToggleRoad25ActionPerformed

    private void jLabelCurveRoadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCurveRoadMouseReleased
        switch (saveButton){
                case 1:
                    jToggleRoad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 2:
                    jToggleRoad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break; 
                case 3:
                    jToggleRoad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 4:
                    jToggleRoad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 5:
                    jToggleRoad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 6:
                    jToggleRoad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 7:
                    jToggleRoad7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 8:
                    jToggleRoad8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 9:
                    jToggleRoad9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 10:
                    jToggleRoad10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 11:
                    jToggleRoad11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 12:
                    jToggleRoad12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 13:
                    jToggleRoad13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 14:
                    jToggleRoad14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 15:
                    jToggleRoad15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 16:
                    jToggleRoad16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 17:
                    jToggleRoad17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 18:
                    jToggleRoad18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 19:
                    jToggleRoad19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 20:
                    jToggleRoad20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 21:    
                    jToggleRoad21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 22:
                    jToggleRoad22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 23:
                    jToggleRoad23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 24:
                    jToggleRoad24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
                case 25:         
                    jToggleRoad25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/curve-road.png")));
                    RotateIcon(0, saveButton, 1);
                    break;
        }
    }//GEN-LAST:event_jLabelCurveRoadMouseReleased

    private void jLabel3WayIntersectionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3WayIntersectionMouseReleased
        switch (saveButton){
                case 1:
                    jToggleRoad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 2:
                    jToggleRoad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break; 
                case 3:
                    jToggleRoad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 4:
                    jToggleRoad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 5:
                    jToggleRoad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 6:
                    jToggleRoad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 7:
                    jToggleRoad7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 8:
                    jToggleRoad8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 9:
                    jToggleRoad9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 10:
                    jToggleRoad10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 11:
                    jToggleRoad11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 12:
                    jToggleRoad12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 13:
                    jToggleRoad13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 14:
                    jToggleRoad14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 15:
                    jToggleRoad15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 16:
                    jToggleRoad16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 17:
                    jToggleRoad17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 18:
                    jToggleRoad18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 19:
                    jToggleRoad19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 20:
                    jToggleRoad20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 21:    
                    jToggleRoad21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 22:
                    jToggleRoad22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 23:
                    jToggleRoad23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 24:
                    jToggleRoad24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
                case 25:         
                    jToggleRoad25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3-way-intersection.png")));
                    RotateIcon(0, saveButton, 2);
                    break;
        }
    }//GEN-LAST:event_jLabel3WayIntersectionMouseReleased

    private void jLabel4WayIntersectionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4WayIntersectionMouseReleased
        switch (saveButton){
                case 1:
                    jToggleRoad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 2:
                    jToggleRoad2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break; 
                case 3:
                    jToggleRoad3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 4:
                    jToggleRoad4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 5:
                    jToggleRoad5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 6:
                    jToggleRoad6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 7:
                    jToggleRoad7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 8:
                    jToggleRoad8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 9:
                    jToggleRoad9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 10:
                    jToggleRoad10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 11:
                    jToggleRoad11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 12:
                    jToggleRoad12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 13:
                    jToggleRoad13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 14:
                    jToggleRoad14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 15:
                    jToggleRoad15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 16:
                    jToggleRoad16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 17:
                    jToggleRoad17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 18:
                    jToggleRoad18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 19:
                    jToggleRoad19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 20:
                    jToggleRoad20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 21:    
                    jToggleRoad21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 22:
                    jToggleRoad22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 23:
                    jToggleRoad23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 24:
                    jToggleRoad24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
                case 25:         
                    jToggleRoad25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4-way-intersection.png")));
                    RotateIcon(0, saveButton, 3);
                    break;
        }
    }//GEN-LAST:event_jLabel4WayIntersectionMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void ButtonToggle(int BNum){
        jToggleRoad1.setSelected(false);
        jToggleRoad2.setSelected(false);
        jToggleRoad3.setSelected(false);
        jToggleRoad4.setSelected(false);
        jToggleRoad5.setSelected(false);
        jToggleRoad6.setSelected(false);
        jToggleRoad7.setSelected(false);
        jToggleRoad8.setSelected(false);
        jToggleRoad9.setSelected(false);
        jToggleRoad10.setSelected(false);
        jToggleRoad11.setSelected(false);
        jToggleRoad12.setSelected(false);
        jToggleRoad13.setSelected(false);
        jToggleRoad14.setSelected(false);
        jToggleRoad15.setSelected(false);
        jToggleRoad16.setSelected(false);
        jToggleRoad17.setSelected(false);
        jToggleRoad18.setSelected(false);
        jToggleRoad19.setSelected(false);
        jToggleRoad20.setSelected(false);
        jToggleRoad21.setSelected(false);
        jToggleRoad22.setSelected(false);
        jToggleRoad23.setSelected(false);
        jToggleRoad24.setSelected(false);
        jToggleRoad25.setSelected(false);

        switch (BNum){
                case 1:
                    jToggleRoad1.setSelected(true);
                    break;
                case 2:
                    jToggleRoad2.setSelected(true);
                    break; 
                case 3:
                    jToggleRoad3.setSelected(true);
                    break;
                case 4:
                    jToggleRoad4.setSelected(true);
                    break;
                case 5:
                    jToggleRoad5.setSelected(true);
                    break;
                case 6:
                    jToggleRoad6.setSelected(true);
                    break;
                case 7:
                    jToggleRoad7.setSelected(true);
                    break;
                case 8:
                    jToggleRoad8.setSelected(true);
                    break;
                case 9:
                    jToggleRoad9.setSelected(true);
                    break;
                case 10:
                    jToggleRoad10.setSelected(true);
                    break;
                case 11:
                    jToggleRoad11.setSelected(true);
                    break;
                case 12:
                    jToggleRoad12.setSelected(true);
                    break;
                case 13:
                    jToggleRoad13.setSelected(true);
                    break;
                case 14:
                    jToggleRoad14.setSelected(true);
                    break;
                case 15:
                    jToggleRoad15.setSelected(true);
                    break;
                case 16:
                    jToggleRoad16.setSelected(true);
                    break;
                case 17:
                    jToggleRoad17.setSelected(true);
                    break;
                case 18:
                    jToggleRoad18.setSelected(true);
                    break;
                case 19:
                    jToggleRoad19.setSelected(true);
                    break;
                case 20:
                    jToggleRoad20.setSelected(true);
                    break;
                case 21:    
                    jToggleRoad21.setSelected(true);
                    break;
                case 22:
                    jToggleRoad22.setSelected(true);
                    break;
                case 23:
                    jToggleRoad23.setSelected(true);
                    break;
                case 24:
                    jToggleRoad24.setSelected(true);
                    break;
                case 25:         
                    jToggleRoad25.setSelected(true);
                    break;
    }
}
    private void RotateIcon(int IconRotation, int BNum, int RoadType){
        switch (BNum){
                case 1:
                    jToggleRoad1.setSelected(true);
                    road1 = RoadType;
                    break;
                case 2:
                    jToggleRoad2.setSelected(true);
                    road2 = RoadType;
                    break; 
                case 3:
                    jToggleRoad3.setSelected(true);
                    road3 = RoadType;
                    break;
                case 4:
                    jToggleRoad4.setSelected(true);
                    road4 = RoadType;
                    break;
                case 5:
                    jToggleRoad5.setSelected(true);
                    road5 = RoadType;
                    break;
                case 6:
                    jToggleRoad6.setSelected(true);
                    road6 = RoadType;
                    break;
                case 7:
                    jToggleRoad7.setSelected(true);
                    road7 = RoadType;
                    break;
                case 8:
                    jToggleRoad8.setSelected(true);
                    road8 = RoadType;
                    break;
                case 9:
                    jToggleRoad9.setSelected(true);
                    road9 = RoadType;
                    break;
                case 10:
                    jToggleRoad10.setSelected(true);
                    road10 = RoadType;
                    break;
                case 11:
                    jToggleRoad11.setSelected(true);
                    road11 = RoadType;
                    break;
                case 12:
                    jToggleRoad12.setSelected(true);
                    road12 = RoadType;
                    break;
                case 13:
                    jToggleRoad13.setSelected(true);
                    road13 = RoadType;
                    break;
                case 14:
                    jToggleRoad14.setSelected(true);
                    road14 = RoadType;
                    break;
                case 15:
                    jToggleRoad15.setSelected(true);
                    road15 = RoadType;
                    break;
                case 16:
                    jToggleRoad16.setSelected(true);
                    road16 = RoadType;
                    break;
                case 17:
                    jToggleRoad17.setSelected(true);
                    road17 = RoadType;
                    break;
                case 18:
                    jToggleRoad18.setSelected(true);
                    road18 = RoadType;
                    break;
                case 19:
                    jToggleRoad19.setSelected(true);
                    road19 = RoadType;
                    break;
                case 20:
                    jToggleRoad20.setSelected(true);
                    road20 = RoadType;
                    break;
                case 21:    
                    jToggleRoad21.setSelected(true);
                    road21 = RoadType;
                    break;
                case 22:
                    jToggleRoad22.setSelected(true);
                    road22 = RoadType;
                    break;
                case 23:
                    jToggleRoad23.setSelected(true);
                    road23 = RoadType;
                    break;
                case 24:
                    jToggleRoad24.setSelected(true);
                    road24 = RoadType;
                    break;
                case 25:         
                    jToggleRoad25.setSelected(true);
                    road25 = RoadType;
                    break;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelStraightRoad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleRoad1;
    private javax.swing.JToggleButton jToggleRoad10;
    private javax.swing.JToggleButton jToggleRoad11;
    private javax.swing.JToggleButton jToggleRoad12;
    private javax.swing.JToggleButton jToggleRoad13;
    private javax.swing.JToggleButton jToggleRoad14;
    private javax.swing.JToggleButton jToggleRoad15;
    private javax.swing.JToggleButton jToggleRoad16;
    private javax.swing.JToggleButton jToggleRoad17;
    private javax.swing.JToggleButton jToggleRoad18;
    private javax.swing.JToggleButton jToggleRoad19;
    private javax.swing.JToggleButton jToggleRoad2;
    private javax.swing.JToggleButton jToggleRoad20;
    private javax.swing.JToggleButton jToggleRoad21;
    private javax.swing.JToggleButton jToggleRoad22;
    private javax.swing.JToggleButton jToggleRoad23;
    private javax.swing.JToggleButton jToggleRoad24;
    private javax.swing.JToggleButton jToggleRoad25;
    private javax.swing.JToggleButton jToggleRoad3;
    private javax.swing.JToggleButton jToggleRoad4;
    private javax.swing.JToggleButton jToggleRoad5;
    private javax.swing.JToggleButton jToggleRoad6;
    private javax.swing.JToggleButton jToggleRoad7;
    private javax.swing.JToggleButton jToggleRoad8;
    private javax.swing.JToggleButton jToggleRoad9;
    // End of variables declaration//GEN-END:variables
}
